config/routes.rb
Rails.application.routes.draw do

  constraints subdomain: 'api' do
    namespace :api, path: '/' do
      namespace :v1, path: '/v1', defaults: { :format => 'json' } do
        resources :customers, only: [:show, :create] do
          member do
            get 'matches', to: 'pet_matches#index'
            post 'adopt', to: 'adoptions#create'
          end
        end

        resources :pets, only: [:show, :create] do
          member do
            get 'matches', to: 'customer_matches#index'
          end
        end

        resources :species
      end
    end
  end

  mount ActionCable.server => '/cable'

  devise_for :admins, path: 'admin',
             path_names: {sign_in: 'sign-in', sign_out: 'sign-out'},
             controllers: { sessions: "admin/sessions" }

  devise_for :customers, path: '',
             path_names: {sign_in: 'sign-in', sign_out: 'sign-out'},
             controllers: { sessions: "sessions" }

  get '/', to: 'dashboard#index', as: 'dashboard'
  resources :pets, only: [:index]
  resources :customer_preferences


  namespace :admin do
    get '/', to: 'dashboard#index', as: 'dashboard'
    resources :admins, only: [:index, :show]

    resources :customer_preferences
    resources :customers
    resources :pets
  end

  resources :events
end

app/models/customer_preference.rb
class CustomerPreference < ApplicationRecord
  belongs_to :customer, :inverse_of => :preferences
  belongs_to :species, optional: true
  belongs_to :breed, optional: true

end

app/controllers/admin/customer_preferences_controller.rb
class Admin::CustomerPreferencesController < Admin::BaseController
  before_action :set_admin_customer_preference, only: [:show, :edit, :update, :destroy]

  # GET /admin/customer_preferences
  # GET /admin/customer_preferences.json
  def index
    @customer_preferences = ::CustomerPreference.all
  end

  # GET /admin/customer_preferences/1
  # GET /admin/customer_preferences/1.json
  def show
  end

  # GET /admin/customer_preferences/new
  def new
    @customer_preference = ::CustomerPreference.new
  end

  # GET /admin/customer_preferences/1/edit
  def edit
  end

  # POST /admin/customer_preferences
  # POST /admin/customer_preferences.json
  def create
    @customer_preference = ::CustomerPreference.new(admin_customer_preference_params)

    respond_to do |format|
      if@customer_preference.save
        format.html { redirect_to [:admin, @customer_preference], notice: 'Customer Preference was successfully created.' }
        format.json { render :show, status: :created, location:@customer_preference }
      else
        format.html { render :new }
        format.json { render json:@customer_preference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/customer_preferences/1
  # PATCH/PUT /admin/customer_preferences/1.json
  def update
    respond_to do |format|
      if@customer_preference.update(admin_customer_preference_params)
        format.html { redirect_to [:admin, @customer_preference], notice: 'Customer Preference was successfully updated.' }
        format.json { render :show, status: :ok, location:@customer_preference }
      else
        format.html { render :edit }
        format.json { render json:@customer_preference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/customer_preferences/1
  # DELETE /admin/customer_preferences/1.json
  def destroy
    @customer_preference.destroy
    respond_to do |format|
      format.html { redirect_to admin_customer_preferences_url, notice: 'Customer Preference was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_admin_customer_preference
    @customer_preference = ::CustomerPreference.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def admin_customer_preference_params
    params.require(:customer_preference).permit(:customer_id, :species_id, :breed_id, :min_age, :max_age)
  end
end

app/controllers/customer_preferences_controller.rb
class CustomerPreferencesController < BaseController
  before_action :set_customer_preference, only: [:show, :edit, :update, :destroy]

  # GET /customer_preferences
  # GET /customer_preferences.json
  def index
    @customer_preferences = current_customer.preferences.all
  end

  # GET /customer_preferences/1
  # GET /customer_preferences/1.json
  def show
  end

  # GET /customer_preferences/new
  def new
    @customer_preference = current_customer.preferences.new
  end

  # GET /customer_preferences/1/edit
  def edit
  end

  # POST /customer_preferences
  # POST /customer_preferences.json
  def create
    @customer_preference = current_customer.preferences.new(customer_preference_params)

    respond_to do |format|
      if@customer_preference.save
        format.html { redirect_to @customer_preference, notice: 'Customer Preference was successfully created.' }
        format.json { render :show, status: :created, location:@customer_preference }
      else
        format.html { render :new }
        format.json { render json: @customer_preference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customer_preferences/1
  # PATCH/PUT /customer_preferences/1.json
  def update
    respond_to do |format|
      if@customer_preference.update(customer_preference_params)
        format.html { redirect_to @customer_preference, notice: 'Customer Preference was successfully updated.' }
        format.json { render :show, status: :ok, location:@customer_preference }
      else
        format.html { render :edit }
        format.json { render json: @customer_preference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customer_preferences/1
  # DELETE /customer_preferences/1.json
  def destroy
    @customer_preference.destroy
    respond_to do |format|
      format.html { redirect_to customer_preferences_url, notice: 'Customer Preference was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_customer_preference
    @customer_preference = current_customer.preferences.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def customer_preference_params
    params.require(:customer_preference).permit(:species_id, :breed_id, :min_age, :max_age)
  end
end

app/helpers/admin/customer_preferences_helper.rb
module Admin::CustomerPreferencesHelper
end

app/views/admin/customer_preferences/_form.html.erb
<% if @customer_preference.errors.any? %>
    <div class="alert fade in alert-danger alert-dismissable"><button aria-hidden="true" class="close" data-dismiss="alert" type="button">×</button>
      <ul>
        <% @customer_preference.errors.full_messages.each do |msg| %>
            <%= content_tag :li, msg, :id => "error_#{msg}" if msg.is_a?(String) %>
        <% end %>
      </ul>
    </div>
<% end %>
<%= simple_form_for([:admin, @customer_preference]) do |f| %>
    <%= f.association :customer %>
    <%= f.association :species, required: false, input_html: {id: :pet_species_id} %>
    <%= f.input :breed_id, collection: Species.all, as: :grouped_select, group_method: :breeds, input_html: {id: :pet_breed_id} %>
    <%= f.input :min_age, label: 'Min age in months' %>
    <%= f.input :max_age, label: 'Min age in months' %>
    <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/admin/customer_preferences/edit.html.erb
<h1>Editing Admin Customer Preference</h1>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'form', admin_customer_preference: @admin_customer_preference %>
      </div>
    </div>
  </div>
</div>

app/views/admin/customer_preferences/index.html.erb
<h1 class="page-title">Customer Preferences</h1>

<div class="row">
  <div class="col-md-12">

    <!-- START DATATABLE EXPORT -->
    <div class="panel panel-default">
      <div class="panel-heading">
        <%= link_to 'New Customer Preference', new_admin_customer_preference_path, class: 'btn btn-primary pull-right' %>

      </div>
      <div class="panel-body">
        <table id="users" class="table datatable">
          <thead>
          <tr>
            <th>Customer ID</th>
            <th>Customer</th>
            <th>Species</th>
            <th>Breed</th>
            <th>Min Age</th>
            <th>Max Age</th>
            <th></th>
          </tr>
          </thead>
          <tbody>
              <% @customer_preferences.each do |customer_preference| %>
                  <tr ng-repeat="customer_preference in customer_preferences">
                    <td><%= customer_preference.customer.id %></td>
                    <td><%= customer_preference.customer %></td>
                    <td><%= customer_preference.species %></td>
                    <td><%= customer_preference.breed %></td>
                    <td><%= customer_preference.min_age %></td>
                    <td><%= customer_preference.max_age %></td>
                    <td class="icon-actions">
                      <%= link_to raw('<i class="fa fa-pencil-square-o" aria-hidden="true"></i>'), edit_admin_customer_preference_path(customer_preference) %>
                      <%= link_to raw('<i class="fa fa-trash-o" aria-hidden="true"></i>'), [:admin, customer_preference], method: :delete, data: { confirm: 'Are you sure?' } %>
                    </td>
                  </tr>
              <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <!-- END DATATABLE EXPORT -->

  </div>
</div>

app/views/admin/customer_preferences/new.html.erb
<h1 class="page-title">New Customer Preference</h1>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'form', admin_customer_preference_path: @customer_preference %>
      </div>
    </div>
  </div>
</div>

app/views/admin/customer_preferences/show.html.erb
<h1 class="page-title">Customer Preference</h1>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= simple_form_for [:admin, @customer_preference], html: {class: 'form-disabled'} do |f| %>
            <%= f.input :customer, readonly: true %>
            <%= f.input :species, readonly: true %>
            <%= f.input :breed, readonly: true %>
            <%= f.input :min_age, readonly: true %>
            <%= f.input :max_age, readonly: true %>
        <% end %>
      </div>
    </div>
  </div>
</div>