config/routes.rb
Rails.application.routes.draw do

  constraints subdomain: 'api' do
    namespace :api, path: '/' do
      namespace :v1, path: '/v1', defaults: { :format => 'json' } do
        resources :customers, only: [:show, :create] do
          member do
            get 'matches', to: 'pet_matches#index'
            post 'adopt', to: 'adoptions#create'
          end
        end

        resources :pets, only: [:show, :create] do
          member do
            get 'matches', to: 'customer_matches#index'
          end
        end

        resources :species
      end
    end
  end

  mount ActionCable.server => '/cable'

  devise_for :admins, path: 'admin',
             path_names: {sign_in: 'sign-in', sign_out: 'sign-out'},
             controllers: { sessions: "admin/sessions" }

  devise_for :customers, path: '',
             path_names: {sign_in: 'sign-in', sign_out: 'sign-out'},
             controllers: { sessions: "sessions" }

  get '/', to: 'dashboard#index', as: 'dashboard'
  resources :pets, only: [:index]
  resources :customer_preferences


  namespace :admin do
    get '/', to: 'dashboard#index', as: 'dashboard'
    resources :admins, only: [:index, :show]

    resources :customer_preferences
    resources :customers
    resources :pets
  end

  resources :events
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :breed
  belongs_to :species
  belongs_to :owner, class_name: 'Customer', foreign_key: :customer_id, optional: true
  has_many :adoptions
  has_many :events, as: :observable
  has_one :location, as: :mappable, inverse_of: :mappable

  after_create_commit { create_event }

  accepts_nested_attributes_for :location, reject_if: :all_blank

  validates_presence_of :name

  def adopted?
    self.owner.is_a?(Customer)
  end

  def matches
    unless self.adopted?
      Customer.find_by_sql(
          [
            'SELECT c.*, p2.customer_id
             FROM customers c
             INNER JOIN customer_preferences cp
                ON (cp.customer_id = c.id)
             INNER JOIN pets p
                ON (cp.species_id IS NULL
                      OR (cp.species_id = p.species_id AND (cp.breed_id IS NULL OR cp.breed_id = p.breed_id)))
             LEFT OUTER JOIN pets p2
                ON c.id = p2.customer_id
             WHERE
                p2.customer_id IS NULL
                AND (cp.min_age IS NULL OR cp.min_age <= ?)
                AND (cp.max_age IS NULL OR cp.max_age >= ?)
                AND p.available_from < ?
             GROUP BY c.id
             ',
              self.age,
              self.age,
              Time.now
          ]
      )
    else
      []
    end
  end

  def to_s
    name
  end

  private

  def create_event
    self.events.create message: 'A new pet named ' + self.name +  ' matching your preferences is now available.'
  end

end

app/controllers/admin/pets_controller.rb
class Admin::PetsController < Admin::BaseController
  before_action :set_admin_pet, only: [:show, :edit, :update, :destroy]

  # GET /admin/pets
  # GET /admin/pets.json
  def index
   @pets = ::Pet.includes(:location).all
  end

  # GET /admin/pets/1
  # GET /admin/pets/1.json
  def show
  end

  # GET /admin/pets/new
  def new
   @pet = ::Pet.new
  end

  # GET /admin/pets/1/edit
  def edit
  end

  # POST /admin/pets
  # POST /admin/pets.json
  def create
   @pet = ::Pet.new(admin_pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to admin_pets_path, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location:@pet }
      else
        format.html { render :new }
        format.json { render json:@pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/pets/1
  # PATCH/PUT /admin/pets/1.json
  def update
    respond_to do |format|
      if@pet.update(admin_pet_params)
        format.html { redirect_to [:admin, @pet], notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location:@pet }
      else
        format.html { render :edit }
        format.json { render json:@pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/pets/1
  # DELETE /admin/pets/1.json
  def destroy
   @pet.destroy
    respond_to do |format|
      format.html { redirect_to admin_pets_url, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_pet
     @pet = ::Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_pet_params
      params.require(:pet).permit(:name, :age, :available_from, :species_id, :breed_id,
                                  location_attributes: [:mappable_id, :mappable_type, :address, :area, :region])
    end
end

app/controllers/api/v1/pets_controller.rb
module API
  module V1
    class PetsController < BaseController
      before_action :set_pet, only: [:show]

      # POST /pets
      def create
        @pet = ::Pet.new(pet_params)
        if @pet.save
          respond_with(@pet, :status => :created, :location => api_v1_pet_path(@pet))
        else
          respond_with(@pet, status: :unprocessable_entity, template: 'shared/error')
        end
      end

      def show
        respond_with(@pet)
      end

      private
      # Use callbacks to share common setup or constraints between actions.
      def set_pet
        @pet = ::Pet.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def pet_params
        params.require(:pet).permit(:name, :age, :available_from, :species_id, :breed_id,
                                    location_attributes: [:mappable_id, :mappable_type, :address, :area, :region])
      end
    end

  end
end

app/helpers/admin/pets_helper.rb
module Admin::PetsHelper
end

app/helpers/api/v1/pets_helper.rb
module API
  module V1
    module PetsHelper



    end
  end
end

app/views/admin/pets/_form.html.erb
<% if @pet.errors.any? %>
    <div class="alert fade in alert-danger alert-dismissable"><button aria-hidden="true" class="close" data-dismiss="alert" type="button">×</button>
      <ul>
        <% @pet.errors.full_messages.each do |msg| %>
            <%= content_tag :li, msg, :id => "error_#{msg}" if msg.is_a?(String) %>
        <% end %>
      </ul>
    </div>
<% end %>
<%= simple_form_for([:admin, @pet]) do |f| %>
    <%= f.input :name %>
    <%= f.input :age, label: 'Min age in months' %>
    <%= f.input :available_from %>
    <%= f.association :species, required: false %>
    <%= f.input :breed_id, collection: Species.all, as: :grouped_select, group_method: :breeds %>
    <%= f.simple_fields_for :location_attributes do |lf| %>
        <%= lf.input :address, required: false %>
        <%= lf.input :area, required: false %>
        <%= lf.input :region, required: false, collection: ['Hong Kong', 'Kowloon', 'New Territories', 'Island'] %>
    <% end %>
    <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/admin/pets/edit.html.erb
<h1 class="page-title">Edit Pet</h1>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'form', admin_pet: [:admin, @pet] %>
      </div>
    </div>
  </div>
</div>

app/views/admin/pets/index.html.erb
<h1 class="page-title">Pets</h1>

<div class="row">
  <div class="col-md-12">

    <!-- START DATATABLE EXPORT -->
    <div class="panel panel-default">
      <div class="panel-heading">
        <%= link_to 'New Pet', new_admin_pet_path, class: 'btn btn-primary pull-right' %>

        <label id="lbl-show">Show: </label>
        <div id="tbl-filters" class="btn-group" data-toggle="buttons">
          <label id="lbl-all" class="btn btn-default active">
            <input type="radio" name="tbl-filter" id="tbl-filter-all" autocomplete="off" value="all" /> All
          </label>
          <label id="lbl-adopted" class="btn btn-default">
            <input type="radio" name="tbl-filter" id="tbl-filter-adopted" autocomplete="off" value="adopted" /> Adopted
          </label>
          <label id="lbl-for-adoption" class="btn btn-default">
            <input type="radio" name="tbl-filter" id="tbl-filter-for-adoption" autocomplete="off" value="for-adoption" /> For Adoption
          </label>
        </div>

      </div>
      <div class="panel-body">


        <table id="users" class="table datatable">
          <thead>
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Age</th>
            <th>Species</th>
            <th>Breed</th>
            <th>Location</th>
            <th>Adopted?</th>
            <th>Adopted by</th>
            <th></th>
          </tr>
          </thead>
          <tbody>
              <% @pets.each do |pet| %>
                  <tr ng-repeat="pet in pets">
                    <td><%= pet.id %></td>
                    <td><%= pet.name %></td>
                    <td><%= pet.age %></td>
                    <td><%= pet.species %></td>
                    <td><%= pet.breed %></td>
                    <td><%= pet.location %></td>
                    <td><%= pet.owner ? 'Yes' : 'No' %></td>
                    <td><%= pet.owner ? link_to(pet.owner.name, admin_customer_path(pet.owner)) : '' %></td>
                    <td class="icon-actions">
                      <%= link_to raw('<i class="fa fa-pencil-square-o" aria-hidden="true"></i>'), edit_admin_pet_path(pet) %>
                      <%= link_to raw('<i class="fa fa-trash-o" aria-hidden="true"></i>'), [:admin, pet], method: :delete, data: { confirm: 'Are you sure?' } %>
                    </td>
                  </tr>
              <% end %>
          </tbody>
        </table>


      </div>
    </div>
    <!-- END DATATABLE EXPORT -->

  </div>
</div>

app/views/admin/pets/new.html.erb
<h1 class="page-title">New Pet</h1>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'form', admin_pet: @pet %>
      </div>
    </div>
  </div>
</div>

app/views/admin/pets/show.html.erb
<h1 class="page-title">Pet</h1>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= simple_form_for [:admin, @pet], html: {class: 'form-disabled'} do |f| %>
            <%= f.input :name, readonly: true %>
            <%= f.input :age, label: 'Min age in months', readonly: true %>
            <%= f.input :available_from, readonly: true %>
            <%= f.input :species, readonly: true %>
            <%= f.input :breed, readonly: true %>
            <%= f.simple_fields_for :location do |lf| %>
                <%= lf.input :address, required: false %>
                <%= lf.input :area, required: false %>
                <%= lf.input :region, required: false, collection: ['Hong Kong', 'Kowloon', 'New Territories', 'Island'] %>
            <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>