config/routes.rb
Rails.application.routes.draw do

  constraints subdomain: 'api' do
    namespace :api, path: '/' do
      namespace :v1, path: '/v1', defaults: { :format => 'json' } do
        resources :customers, only: [:show, :create] do
          member do
            get 'matches', to: 'pet_matches#index'
            post 'adopt', to: 'adoptions#create'
          end
        end

        resources :pets, only: [:show, :create] do
          member do
            get 'matches', to: 'customer_matches#index'
          end
        end

        resources :species
      end
    end
  end

  mount ActionCable.server => '/cable'

  devise_for :admins, path: 'admin',
             path_names: {sign_in: 'sign-in', sign_out: 'sign-out'},
             controllers: { sessions: "admin/sessions" }

  devise_for :customers, path: '',
             path_names: {sign_in: 'sign-in', sign_out: 'sign-out'},
             controllers: { sessions: "sessions" }

  get '/', to: 'dashboard#index', as: 'dashboard'
  resources :pets, only: [:index]
  resources :customer_preferences


  namespace :admin do
    get '/', to: 'dashboard#index', as: 'dashboard'
    resources :admins, only: [:index, :show]

    resources :customer_preferences
    resources :customers
    resources :pets
  end

  resources :events
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Admin</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />

  <link rel="icon" href="favicon.ico" type="image/x-icon" />

  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

</head>
<body>
<!-- START PAGE CONTAINER -->
<div class="page-container">

  <!-- START PAGE SIDEBAR -->
  <div class="page-sidebar">
    <!-- START X-NAVIGATION -->
    <ul class="x-navigation">
      <li class="xn-logo">
        <a href="index.html">Admin</a>
        <a href="#" class="x-navigation-control"></a>
      </li>
      <li class="xn-profile">
        <a href="#" class="profile-mini">
          <%= image_tag ('avatar.png') %>
        </a>
        <div class="profile">
          <div class="profile-image">
            <%= image_tag ('avatar.png') %>
          </div>
          <div class="profile-data">
            <div class="profile-data-name">Pets</div>
            <div class="profile-data-title">Administrator</div>
          </div>
        </div>
      </li>
      <li class="xn-title"></li>
      <li class="<%= current_page?(admin_dashboard_path) ? 'active' : '' %>">
        <a href="<%= admin_dashboard_path %>"><span class="fa fa-desktop"></span> <span class="xn-text">Dashboard</span></a>
      </li>
      <li class="<%= current_page?(admin_pets_path) ? 'active' : '' %>">
        <a href="<%= admin_pets_path %>"><span class="fa fa-paw"></span> <span class="xn-text">Pets</span></a>
      </li>
      <li class="<%= current_page?(admin_customers_path) ? 'active' : '' %>">
        <a href="<%= admin_customers_path %>"><span class="fa fa-user"></span> <span class="xn-text">Customers</span></a>
      </li>
      <li class="<%= current_page?(admin_customer_preferences_path) ? 'active' : '' %>">
        <a href="<%= admin_customer_preferences_path %>"><span class="fa fa-user"></span> <span class="xn-text">Customer Preferences</span></a>
      </li>
    </ul>
    <!-- END X-NAVIGATION -->
  </div>
  <!-- END PAGE SIDEBAR -->

  <!-- PAGE CONTENT -->
  <div class="page-content">

    <!-- START X-NAVIGATION VERTICAL -->
    <ul class="x-navigation x-navigation-horizontal x-navigation-panel">
      <!-- TOGGLE NAVIGATION -->
      <li class="xn-icon-button">
        <a href="#" class="x-navigation-minimize"><span class="fa fa-dedent"></span></a>
      </li>
      <!-- END TOGGLE NAVIGATION -->
      <!-- SEARCH -->
      <li class="xn-search">
        <form role="form">
          <input type="text" name="search" placeholder="Search..."/>
        </form>
      </li>
      <!-- END SEARCH -->
      <!-- SIGN OUT -->
      <li class="xn-icon-button pull-right">
        <a href="#" class="mb-control" data-box="#mb-signout"><span class="fa fa-sign-out"></span></a>
      </li>
      <!-- END SIGN OUT -->

    </ul>
    <!-- END X-NAVIGATION VERTICAL -->

    <!-- START BREADCRUMB -->
    <ul class="breadcrumb">
      <li><a href="<%= admin_dashboard_path %>">Dashboard</a></li>
    </ul>
    <!-- END BREADCRUMB -->

    <!-- PAGE CONTENT WRAPPER -->
    <div class="page-content-wrap">

      <%= render 'shared/notifications' %>

      <%= yield %>

    </div>
    <!-- END PAGE CONTENT WRAPPER -->
  </div>
  <!-- END PAGE CONTENT -->
</div>
<!-- END PAGE CONTAINER -->

<!-- MESSAGE BOX-->
<div class="message-box animated fadeIn" data-sound="alert" id="mb-signout">
  <div class="mb-container">
    <div class="mb-middle">
      <div class="mb-title"><span class="fa fa-sign-out"></span> Log <strong>Out</strong> ?</div>
      <div class="mb-content">
        <p>Are you sure you want to log out?</p>
        <p>Press No if youwant to continue work. Press Yes to logout current user.</p>
      </div>
      <div class="mb-footer">
        <div class="pull-right">
          <%= link_to "Yes", destroy_admin_session_url, :method => :delete, :class => "btn btn-success btn-lg" %>
          <button class="btn btn-default btn-lg mb-control-close">No</button>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- END MESSAGE BOX-->
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Pets.local</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />

  <link rel="icon" href="favicon.ico" type="image/x-icon" />

  <%= csrf_meta_tags %>

  <%= action_cable_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

</head>
<body>
<!-- START PAGE CONTAINER -->
<div class="page-container">

  <!-- START PAGE SIDEBAR -->
  <div class="page-sidebar">
    <!-- START X-NAVIGATION -->
    <ul class="x-navigation">
      <li class="xn-logo">
        <a href="index.html">CPanel</a>
        <a href="#" class="x-navigation-control"></a>
      </li>
      <li class="xn-profile">
        <a href="#" class="profile-mini">
          <%= image_tag ('avatar.png') %>
        </a>
        <div class="profile">
          <div class="profile-image">
            <%= image_tag ('avatar.png') %>
          </div>
          <div class="profile-data">
            <div class="profile-data-name"><%= current_customer.name %></div>
            <div class="profile-data-title">Customer</div>
          </div>
        </div>
      </li>
      <li class="xn-title"></li>
      <li class="<%= current_page?(dashboard_path) ? 'active' : '' %>">
        <a href="<%= dashboard_path %>"><span class="fa fa-desktop"></span> <span class="xn-text">Dashboard</span></a>
      </li>
      <li class="<%= current_page?(customer_preferences_path) ? 'active' : '' %>">
        <a href="<%= customer_preferences_path %>"><span class="fa fa-user"></span> <span class="xn-text">My Preferences</span></a>
      </li>
    </ul>
    <!-- END X-NAVIGATION -->
  </div>
  <!-- END PAGE SIDEBAR -->

  <!-- PAGE CONTENT -->
  <div class="page-content">

    <!-- START X-NAVIGATION VERTICAL -->
    <ul class="x-navigation x-navigation-horizontal x-navigation-panel">
      <!-- TOGGLE NAVIGATION -->
      <li class="xn-icon-button">
        <a href="#" class="x-navigation-minimize"><span class="fa fa-dedent"></span></a>
      </li>
      <!-- END TOGGLE NAVIGATION -->
      <!-- SEARCH -->
      <li class="xn-search">
        <form role="form">
          <input type="text" name="search" placeholder="Search..."/>
        </form>
      </li>
      <!-- END SEARCH -->
      <!-- SIGN OUT -->
      <li class="xn-icon-button pull-right">
        <a href="#" class="mb-control" data-box="#mb-signout"><span class="fa fa-sign-out"></span></a>
      </li>
      <!-- END SIGN OUT -->

    </ul>
    <!-- END X-NAVIGATION VERTICAL -->

    <!-- START BREADCRUMB -->
    <ul class="breadcrumb">
      <li><a href="<%= dashboard_path %>">Dashboard</a></li>
    </ul>
    <!-- END BREADCRUMB -->

    <!-- PAGE CONTENT WRAPPER -->
    <div class="page-content-wrap">

      <%= render 'shared/notifications' %>

      <%= yield %>

    </div>
    <!-- END PAGE CONTENT WRAPPER -->
  </div>
  <!-- END PAGE CONTENT -->
</div>
<!-- END PAGE CONTAINER -->

<!-- MESSAGE BOX-->
<div class="message-box animated fadeIn" data-sound="alert" id="mb-signout">
  <div class="mb-container">
    <div class="mb-middle">
      <div class="mb-title"><span class="fa fa-sign-out"></span> Log <strong>Out</strong> ?</div>
      <div class="mb-content">
        <p>Are you sure you want to log out?</p>
        <p>Press No if youwant to continue work. Press Yes to logout current user.</p>
      </div>
      <div class="mb-footer">
        <div class="pull-right">
          <%= link_to "Yes", destroy_customer_session_url, :method => :delete, :class => "btn btn-success btn-lg" %>
          <button class="btn btn-default btn-lg mb-control-close">No</button>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- END MESSAGE BOX-->
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html lang="en" class="body-full-height">
<head>
  <title>Login - Pets.local</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />

  <link rel="icon" href="favicon.ico" type="image/x-icon" />

  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>

<div class="login-container">

  <div class="login-box animated fadeInDown">

    <%= render 'shared/notifications' %>

    <div class="login-body">
      <div class="login-title"><strong>Login</strong></div>


      <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
          <div class="form-group has-feedback">
            <%= f.text_field :email, class: 'form-control', placeholder: 'Email', autofocus: true %>
            <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
          </div>

          <div class="form-group has-feedback">
            <%= f.password_field :password, class: 'form-control', placeholder: 'Password', autocomplete: 'off' %>
            <span class="glyphicon glyphicon-lock form-control-feedback"></span>
          </div>
          <div class="form-group">
            <div class="col-xs-6"></div>
            <div class="col-xs-6">
              <%= f.submit 'Sign in', class: 'btn btn-info btn-primary btn-block btn-flat' %>
            </div><!-- /.col -->
          </div>
      <% end %>

    </div>
    <div class="login-footer">
      <div class="pull-left">&copy; 2016 Pets Inc.</div>
    </div>
  </div>

</div>

</body>
</html>





